name: ARC Test

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Show Hostname
        run: hostname

      - name: Show Date
        run: date

      - name: Hello
        run: echo "ARC runner works!"
