name: ARC Kubernetes Validation

on:
  workflow_dispatch:

jobs:
  arc-validation:
    runs-on: self-hosted

    steps:

      - name: Show Hostname
        run: hostname

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.34.1/bin/linux/amd64/kubectl"
          chmod +x kubectl
          ./kubectl version --client

      - name: Check Service Account
        run: |
          ls -la /var/run/secrets/kubernetes.io/serviceaccount/ || true
