name: Kubernetes Discovery

on:
  workflow_dispatch:

jobs:
  cluster-check:
    runs-on: [self-hosted, jumpbox]

    steps:
      - name: Show Hostname
        run: hostname

      - name: Show Current User
        run: whoami

      - name: Show Kubernetes Nodes
        run: ssh orlando@192.168.1.210 "kubectl get nodes"

      - name: Show All Pods
        run: ssh orlando@192.168.1.210 "kubectl get pods -A"
